pull_request_rules:
  - name: automatic merge when CI passes and 2 reviews
    conditions:
      - label=merge
      - status-success=Travis CI - Pull Request
      - base=master
    actions:
      merge:
        method: merge
