# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4



env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fhPfSCyhYrG8HT3No1DJkPqmv2uJg0lCrLRD3ofbxQD25rqkYFAuenVZdqrvygZO/xsArjG81la0VdkZyeTMheSod3G0wzJ+eaYVz3FUcg8Jg2GEb4zjx7g1Tq6MisZwvPUEo80QAXiQ65gKGAI6Ux02eYH1JuRpQlrbQMSpYmdHyuncg7vS86f9xLizwki/InIq+ZgQxlqkK7tiaulDIRFAqGuCViHns+6rtE7ncfj+bMKwBwIR7d3UdkQ8lyGWiPxqIvjUIuJY+rHdhN4Vg9TP7eJim8u03L2KorsXhLjoVJWYlF5IAMQAysyzxXIzS8D80ph9eWUP8ZST1Hb+V40odlaSvLTI/8siIsxEfb9oVMaw3Tr/AMyoXFH75Onk4pB2dmEswA1lncZTLegDv92K6JBl+624iVDAqbh9cpc6PWajX9rEITdk8r/bYC3FzNYMMBY9QQc3/B1F6oxYyKRW6avzFZLjler71G1VfKZvs/NpRw2l4xGCWOfOHt7MDeVmCbnrcyreS8DVokeiesxnA5z/ap6rnCDc/2JfrZhM3ux7y03vFZBE8jKDpEnACNMhyiWonKUs25iAyDfRSdAdJGfrN5ScakzMXkh0+kiZPZAfklidVs/KVG4rl6lp4N/EgZ5aiwhq3RJ5q3VAVHuDYtJltzbRqJIOOuV8gII="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
